name: Minigames
main: xyz.derkades.minigames.Minigames
version: 1.0
author: Derkades
authors: [Corrupt_World]
softdepend: [Vault, Citizens]
api-version: 1.16

commands:
  games:
    aliases: ['.']
  bug:
    usage: /<command>
    aliases: [feedback, idea]
  dm90ZSEh:
    usage: /<command> HI HOW ARE YOU DOING
  spectate:
    aliases: [spec]
  wtp:
  