name: Minigames
main: derkades.minigames.Minigames
version: 1.0
author: Derkades
authors: [Corrupt_World]
softdepend: [Vault, Citizens]
api-version: 1.16

commands:
  games:
    aliases: ['.', 'g']
  bug:
    usage: /<command>
    aliases: [feedback, idea]
  spectate:
    aliases: [spec]
  wtp:
  testworld:
  voteskip:
    aliases: [skip]
