name: Minigames
main: xyz.derkades.minigames.Minigames
version: 6.9
author: RobinMC
description: ohiasohidfasdasimasm
softdepend: [Vault, Citizens]

api-version: 1.13

commands:
  games:
    aliases: ['.']
  bug:
    usage: /<command>
    aliases: [feedback, idea]
  dm90ZSEh:
    usage: /<command> HI HOW ARE YOU DOING
  spectate:
    aliases: [spec]
  wtp:
  