name: Minigames
main: xyz.derkades.minigames.Minigames
version: 6.9
author: RobinMC
description: ohiasohidfasdasimasm
depends: [nuvotifier]

api-version: 1.13

commands:
  games:
    usage: /<command>
    aliases: [g]
  bug:
    usage: /<command>
    aliases: [feedback, idea]